from __future__ import annotations

# Metadata for graph viewer only. This does not affect runtime behavior.
GRAPH_METADATA: dict[str, dict] = {
    "world": {
        "title": "WorldGraph",
        "description": "Control-plane orchestration and agent dispatch loop.",
        "transitions": [
            {"source": "__start__", "target": "ingest_world_commands", "type": "edge", "note": "entry"},
            {"source": "ingest_world_commands", "target": "ingest_events", "type": "edge", "note": ""},
            {"source": "ingest_events", "target": "refresh_registry_and_scope", "type": "edge", "note": ""},
            {"source": "refresh_registry_and_scope", "target": "route_scope", "type": "edge", "note": ""},
            {"source": "route_scope", "target": "schedule_agent_tasks", "type": "edge", "note": ""},
            {
                "source": "schedule_agent_tasks",
                "target": "run_agent",
                "type": "send",
                "note": "LangGraph Send fan-out, one task per runnable agent",
            },
            {"source": "schedule_agent_tasks", "target": "collect_agent_outputs", "type": "conditional", "note": "no runnable tasks"},
            {"source": "run_agent", "target": "collect_agent_outputs", "type": "edge", "note": "fan-in"},
            {"source": "collect_agent_outputs", "target": "broker_mentions_and_replies", "type": "edge", "note": ""},
            {"source": "broker_mentions_and_replies", "target": "commit_events", "type": "edge", "note": ""},
            {"source": "commit_events", "target": "publish_updates", "type": "edge", "note": ""},
            {"source": "publish_updates", "target": "world_loop_gate", "type": "edge", "note": ""},
            {
                "source": "world_loop_gate",
                "target": "ingest_world_commands",
                "type": "loop",
                "note": "world_running=true and pending workload and world_tick<max",
            },
            {"source": "world_loop_gate", "target": "__end__", "type": "conditional", "note": "stop or idle"},
        ],
        "nodes": {
            "ingest_world_commands": {
                "title": "Ingest Commands",
                "description": "Validate and apply world commands via pluggable handlers.",
                "source_file": "src/graphchat/application/nodes/world_nodes.py",
                "state_fields": ["world_commands", "pending_injections", "pending_direct_chats", "world_outputs"],
            },
            "ingest_events": {
                "title": "Ingest Events",
                "description": "Validate external events and append to pending queue.",
                "source_file": "src/graphchat/application/nodes/world_nodes.py",
                "state_fields": ["incoming_events", "pending_events"],
            },
            "refresh_registry_and_scope": {
                "title": "Refresh Registry",
                "description": "Refresh enabled agents and latest status snapshot.",
                "source_file": "src/graphchat/application/nodes/world_nodes.py",
                "state_fields": ["agents", "agent_status_map"],
            },
            "route_scope": {
                "title": "Route Scope",
                "description": "Resolve event visibility by group/dm scope rules.",
                "source_file": "src/graphchat/application/nodes/world_nodes.py",
                "state_fields": ["pending_events", "routed_events_by_agent"],
            },
            "schedule_agent_tasks": {
                "title": "Schedule Tasks",
                "description": "Merge routed events + injections + pending mentions into per-agent tasks.",
                "source_file": "src/graphchat/application/nodes/world_nodes.py",
                "state_fields": ["agent_tasks", "runnable_agents", "pending_injections", "pending_mentions"],
            },
            "run_agent": {
                "title": "Run Agent",
                "description": "Dispatch each task in parallel via LangGraph Send.",
                "source_file": "src/graphchat/application/nodes/world_nodes.py",
                "state_fields": ["agent_task", "agent_outputs"],
            },
            "collect_agent_outputs": {
                "title": "Collect Outputs",
                "description": "Aggregation point for parallel agent outputs.",
                "source_file": "src/graphchat/application/nodes/world_nodes.py",
                "state_fields": ["agent_outputs"],
            },
            "broker_mentions_and_replies": {
                "title": "Mention Broker",
                "description": "Validate mentions, generate direct replies, or queue follow-up mentions.",
                "source_file": "src/graphchat/application/nodes/world_nodes.py",
                "state_fields": ["agent_outputs", "world_outputs", "pending_mentions", "pending_direct_chats"],
            },
            "commit_events": {
                "title": "Commit Events",
                "description": "Persist deduplicated events to store.",
                "source_file": "src/graphchat/application/nodes/world_nodes.py",
                "state_fields": ["agent_outputs", "world_outputs", "committed_event_ids", "latest_events"],
            },
            "publish_updates": {
                "title": "Publish Updates",
                "description": "Expose latest committed events for API/stream consumers.",
                "source_file": "src/graphchat/application/nodes/world_nodes.py",
                "state_fields": ["published_events", "latest_events"],
            },
            "world_loop_gate": {
                "title": "Loop Gate",
                "description": "Bound loop continuation by running flag, stop flag, backlog, and max ticks.",
                "source_file": "src/graphchat/application/nodes/world_nodes.py",
                "state_fields": ["world_running", "stop_requested", "world_tick", "max_world_ticks_per_run"],
            },
        },
    },
    "agent": {
        "title": "AgentGraph",
        "description": "Planner-executor agent graph with explicit plan node and execution node.",
        "transitions": [
            {"source": "__start__", "target": "listening_subgraph", "type": "edge", "note": ""},
            {"source": "listening_subgraph", "target": "decide_wake", "type": "edge", "note": ""},
            {"source": "decide_wake", "target": "plan_action", "type": "conditional", "note": "wake"},
            {"source": "decide_wake", "target": "__end__", "type": "conditional", "note": "sleep/idle"},
            {"source": "plan_action", "target": "action_parallel_subgraph", "type": "edge", "note": "normalize actions[] into plan steps"},
            {"source": "action_parallel_subgraph", "target": "skill_execution_subgraph", "type": "edge", "note": "explicit execution stage"},
            {"source": "skill_execution_subgraph", "target": "lifecycle_gate", "type": "edge", "note": ""},
            {"source": "lifecycle_gate", "target": "listening_subgraph", "type": "loop", "note": "task_done and internal loop enabled"},
            {"source": "lifecycle_gate", "target": "decide_wake", "type": "loop", "note": "continue working"},
            {"source": "lifecycle_gate", "target": "__end__", "type": "conditional", "note": "sleep/stop"},
        ],
        "nodes": {
            "listening_subgraph": {
                "title": "Listening Subgraph",
                "source_file": "src/graphchat/application/graphs/subgraphs/listening_subgraph.py",
                "state_fields": ["last_event", "silent_rounds", "global_ttl", "should_wake"],
                "subgraph_id": "listening_subgraph",
            },
            "decide_wake": {
                "title": "Decide Wake",
                "source_file": "src/graphchat/application/nodes/agent_nodes.py",
                "state_fields": ["should_wake", "phase_override"],
            },
            "plan_action": {
                "title": "Plan Action",
                "source_file": "src/graphchat/application/nodes/agent_nodes.py",
                "state_fields": ["planned_actions", "planned_action", "task_done"],
            },
            "action_parallel_subgraph": {
                "title": "Plan Subgraph",
                "source_file": "src/graphchat/application/graphs/subgraphs/action_parallel_subgraph.py",
                "state_fields": ["planned_actions", "plan_steps", "executed_step_ids", "skill_context"],
                "subgraph_id": "action_parallel_subgraph",
            },
            "skill_execution_subgraph": {
                "title": "Skill Execution Subgraph",
                "source_file": "src/graphchat/application/graphs/subgraphs/skill_execution_subgraph.py",
                "state_fields": ["plan_steps", "action_results", "emitted_events", "plan_execution_report", "global_ttl"],
                "subgraph_id": "skill_execution_subgraph",
            },
            "lifecycle_gate": {
                "title": "Lifecycle Gate",
                "source_file": "src/graphchat/application/nodes/agent_nodes.py",
                "state_fields": ["global_ttl", "task_done", "agent_status"],
            },
        },
    },
    "listening_subgraph": {"title": "ListeningSubgraph", "description": "Listening + silent loop."},
    "silent_loop_subgraph": {"title": "SilentLoopSubgraph", "description": "Silent polling loop."},
    "retrieval_subgraph": {"title": "RetrievalSubgraph", "description": "Retrieval channel selection + ranking."},
    "action_parallel_subgraph": {
        "title": "ActionParallelSubgraph",
        "description": "Plan normalization stage before explicit execution subgraph.",
        "nodes": {
            "prepare_plan": {
                "title": "Prepare Plan",
                "description": "Normalize actions and fill dependencies.",
                "source_file": "src/graphchat/application/graphs/subgraphs/action_parallel_subgraph.py",
                "state_fields": ["planned_actions", "plan_steps"],
            },
        },
    },
    "skill_execution_subgraph": {
        "title": "SkillExecutionSubgraph",
        "description": "Execute plan steps through explicit skill lanes and per-step guards.",
        "transitions": [
            {"source": "__start__", "target": "select_ready_steps", "type": "edge", "note": ""},
            {
                "source": "select_ready_steps",
                "target": "skill_rag",
                "type": "send",
                "note": "parallel step dispatch (rag lane)",
            },
            {
                "source": "select_ready_steps",
                "target": "skill_board",
                "type": "send",
                "note": "parallel step dispatch (board lane)",
            },
            {
                "source": "select_ready_steps",
                "target": "skill_governance",
                "type": "send",
                "note": "parallel step dispatch (governance lane)",
            },
            {
                "source": "select_ready_steps",
                "target": "skill_dialog",
                "type": "send",
                "note": "parallel step dispatch (dialog lane)",
            },
            {
                "source": "select_ready_steps",
                "target": "skill_generic",
                "type": "send",
                "note": "parallel step dispatch (generic lane)",
            },
            {"source": "select_ready_steps", "target": "finalize_plan", "type": "conditional", "note": "no ready steps"},
            {"source": "skill_rag", "target": "merge_wave", "type": "edge", "note": ""},
            {"source": "skill_board", "target": "merge_wave", "type": "edge", "note": ""},
            {"source": "skill_governance", "target": "merge_wave", "type": "edge", "note": ""},
            {"source": "skill_dialog", "target": "merge_wave", "type": "edge", "note": ""},
            {"source": "skill_generic", "target": "merge_wave", "type": "edge", "note": ""},
            {"source": "merge_wave", "target": "select_ready_steps", "type": "loop", "note": "has remaining steps and ttl > 0"},
            {"source": "merge_wave", "target": "finalize_plan", "type": "conditional", "note": "ttl exhausted or done"},
            {"source": "finalize_plan", "target": "__end__", "type": "edge", "note": ""},
        ],
        "nodes": {
            "select_ready_steps": {
                "title": "Select Ready Steps",
                "description": "Pick dependency-ready steps for this wave.",
                "source_file": "src/graphchat/application/graphs/subgraphs/skill_execution_subgraph.py",
                "state_fields": ["plan_steps", "executed_step_ids", "ready_steps"],
            },
            "skill_rag": {
                "title": "Skill Lane: Rag",
                "description": "Run retrieval-centric skill step with per-step guards.",
                "source_file": "src/graphchat/application/graphs/subgraphs/skill_execution_subgraph.py",
                "state_fields": ["current_step", "step_results", "action_results", "emitted_events"],
            },
            "skill_board": {
                "title": "Skill Lane: Board",
                "description": "Run board mutation skill step with per-step guards.",
                "source_file": "src/graphchat/application/graphs/subgraphs/skill_execution_subgraph.py",
                "state_fields": ["current_step", "step_results", "action_results", "emitted_events"],
            },
            "skill_governance": {
                "title": "Skill Lane: Governance",
                "description": "Run governance skill step with per-step guards.",
                "source_file": "src/graphchat/application/graphs/subgraphs/skill_execution_subgraph.py",
                "state_fields": ["current_step", "step_results", "action_results", "emitted_events"],
            },
            "skill_dialog": {
                "title": "Skill Lane: Dialog",
                "description": "Run communication skill step with per-step guards.",
                "source_file": "src/graphchat/application/graphs/subgraphs/skill_execution_subgraph.py",
                "state_fields": ["current_step", "step_results", "action_results", "emitted_events"],
            },
            "skill_generic": {
                "title": "Skill Lane: Generic",
                "description": "Run generic skill step with per-step guards.",
                "source_file": "src/graphchat/application/graphs/subgraphs/skill_execution_subgraph.py",
                "state_fields": ["current_step", "step_results", "action_results", "emitted_events"],
            },
            "merge_wave": {
                "title": "Merge Wave",
                "description": "Merge parallel branch outputs and update ttl/context.",
                "source_file": "src/graphchat/application/graphs/subgraphs/skill_execution_subgraph.py",
                "state_fields": ["wave_step_ids", "wave_context_patches", "executed_step_ids", "global_ttl"],
            },
            "finalize_plan": {
                "title": "Finalize Plan",
                "description": "Write final action results back to parent state.",
                "source_file": "src/graphchat/application/graphs/subgraphs/skill_execution_subgraph.py",
                "state_fields": ["action_results", "planned_action", "action_payload", "plan_execution_report"],
            },
        },
    },
    "board_subgraph": {"title": "BoardSubgraph", "description": "Task board mutation flow."},
    "governance_subgraph": {"title": "GovernanceSubgraph", "description": "Governance actions."},
    "guardrail_subgraph": {"title": "GuardrailSubgraph", "description": "Policy/schema/idempotency guard chain."},
}
